### PR TITLE
fixed notification overwrites

### PR DESCRIPTION
**Pull request by msupino**

### CODE REVIEW

**Comment by claudio-viola** [comment]
I cannot build the application with this new fix..
go get github.com/AcalephStorage/consul-alerts
 go install
./check-handler.go:129: alert.CheckId undefined (type consul.Check has no field or method CheckId, but does have CheckID)

Can you please revert until fixed?

**Comment by msupino** [comment]
i cant revert, i down own this repo, you can compile mine until the merge is approved

**Comment by msupino** [comment]
can u please merge again ? build it broken

Marco.

**Comment by msupino** [comment]
merge done, build shoudl pass.

Marco.

**Pull request merged**
