### PR TITLE
add vagrant support

### PR DESCRIPTION
**Pull request by devpopol**
Adding so that contributors can have easier time setting up local development environment.

### CODE REVIEW

**Comment by devpopol** [comment]
#### booting the VM
```
devpopol@popol consul-alerts (vagrant-support) $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'consul-alerts'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: consul-alerts_default_1424910003181_86976
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/devpopol/dev/files/rails/musashibox/consul-alerts
==> default: Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [git | Install git] ***************************************************** 
changed: [default]

TASK: [go | Get Go binaries] ************************************************** 
changed: [default]

TASK: [go | Extract Go binaries] ********************************************** 
changed: [default]

TASK: [go | Set PATH and GOPATH] ********************************************** 
changed: [default] => (item=export GOPATH=/home/vagrant)
changed: [default] => (item=export PATH=$PATH:/usr/local/go/bin)

TASK: [consul | file path={{consul_dest}} state=directory] ******************** 
changed: [default]

TASK: [consul | get_url url={{consul_download_url}} dest={{consul_dest}}] ***** 
changed: [default]

TASK: [consul | apt name=unzip update_cache=yes] ****************************** 
changed: [default]

TASK: [consul | unarchive src={{consul_dest}}/{{consul_filename}} dest=/usr/local/bin copy=no] *** 
changed: [default]

TASK: [consul | copy src=run-consul dest=/usr/local/bin mode=755] ************* 
changed: [default]

TASK: [consul-alerts | file path="{{go_gopath}}/src/github.com/AcalephStorage" state=directory recurse=yes owner=vagrant group=vagrant] *** 
changed: [default]

TASK: [consul-alerts | file dest="{{go_gopath}}/src/github.com/AcalephStorage/consul-alerts" src=/vagrant state=link] *** 
changed: [default]

TASK: [consul-alerts | file path="{{go_gopath}}" state=directory owner=vagrant group=vagrant recurse=yes] *** 
changed: [default]

PLAY RECAP ******************************************************************** 
default                    : ok=13   changed=12   unreachable=0    failed=0   
```

### Working inside the VM
```
devpopol@popol consul-alerts (vagrant-support) $ vagrant ssh
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

 System information disabled due to load higher than 1.0

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Thu Feb 26 00:25:47 2015 from 10.0.2.2
_____________________________________________________________________
WARNING! Your environment specifies an invalid locale.
 This can affect your user experience significantly, including the
 ability to manage packages. You may install the locales by running:

   sudo apt-get install language-pack-UTF-8
     or
   sudo locale-gen UTF-8

To see all available language packs, run:
   apt-cache search "^language-pack-[a-z][a-z]$"
To disable this message for all users, run:
   sudo touch /var/lib/cloud/instance/locale-check.skip
_____________________________________________________________________

vagrant@vagrant-ubuntu-trusty-64:~$ cd src/github.com/AcalephStorage/consul-alerts
vagrant@vagrant-ubuntu-trusty-64:~/src/github.com/AcalephStorage/consul-alerts$ go get
vagrant@vagrant-ubuntu-trusty-64:~/src/github.com/AcalephStorage/consul-alerts$ go build
vagrant@vagrant-ubuntu-trusty-64:~/src/github.com/AcalephStorage/consul-alerts$ run-consul
vagrant@vagrant-ubuntu-trusty-64:~/src/github.com/AcalephStorage/consul-alerts$ nohup: appending output to 'nohup.out'

vagrant@vagrant-ubuntu-trusty-64:~/src/github.com/AcalephStorage/consul-alerts$ ./consul-alerts start
INFO[0000] Checking consul agent connection...          
INFO[0000] Registering new health check: node=vagrant-ubuntu-trusty-64, service=, check=Serf Health Status, status=passing 
INFO[0000] Consul Alerts daemon started                 
INFO[0000] Consul Alerts Host: vagrant-ubuntu-trusty-64 
INFO[0000] Consul Agent: localhost:8500                 
INFO[0000] Consul Datacenter: dc1                       
INFO[0000] vagrant-ubuntu-trusty-64 has become the leader. 
```

**Comment by darkcrux** [comment]
Cool. Should speed up dev. Do you think we should have at least 2 or 3 vm instances of consul, for working with leader elections and all?

**Comment by devpopol** [comment]
yeah, i think that would be better. will settle for 3 since that's an odd number.

**Comment by devpopol** [comment]
### Setup

```
devpopol@popol consul-alerts (vagrant-support) $ vagrant destroy -f && vagrant up
==> node3: Forcing shutdown of VM...
==> node3: Destroying VM and associated drives...
==> node3: Running cleanup tasks for 'ansible' provisioner...
==> node2: Forcing shutdown of VM...
==> node2: Destroying VM and associated drives...
==> node2: Running cleanup tasks for 'ansible' provisioner...
==> node1: Forcing shutdown of VM...
==> node1: Destroying VM and associated drives...
==> node1: Running cleanup tasks for 'ansible' provisioner...
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node3' up with 'virtualbox' provider...
==> node1: Importing base box 'consul-alerts'...
==> node1: Matching MAC address for NAT networking...
==> node1: Setting the name of the VM: consul-alerts_node1_1424936999002_96440
==> node1: Clearing any previously set forwarded ports...
==> node1: Clearing any previously set network interfaces...
==> node1: Preparing network interfaces based on configuration...
    node1: Adapter 1: nat
    node1: Adapter 2: hostonly
==> node1: Forwarding ports...
    node1: 22 => 2222 (adapter 1)
==> node1: Running 'pre-boot' VM customizations...
==> node1: Booting VM...
==> node1: Waiting for machine to boot. This may take a few minutes...
    node1: SSH address: 127.0.0.1:2222
    node1: SSH username: vagrant
    node1: SSH auth method: private key
    node1: Warning: Connection timeout. Retrying...
    node1: Warning: Remote connection disconnect. Retrying...
==> node1: Machine booted and ready!
==> node1: Checking for guest additions in VM...
==> node1: Setting hostname...
==> node1: Configuring and enabling network interfaces...
==> node1: Mounting shared folders...
    node1: /vagrant => /Users/devpopol/dev/files/rails/musashibox/consul-alerts
==> node1: Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [node1]

TASK: [git | Install git] ***************************************************** 
changed: [node1]

TASK: [go | Get Go binaries] ************************************************** 
changed: [node1]

TASK: [go | Extract Go binaries] ********************************************** 
changed: [node1]

TASK: [go | Set PATH and GOPATH] ********************************************** 
changed: [node1] => (item=export GOPATH=/home/vagrant)
changed: [node1] => (item=export PATH=$PATH:/usr/local/go/bin)

TASK: [consul | file path={{consul_dest}} state=directory] ******************** 
changed: [node1]

TASK: [consul | get_url url={{consul_download_url}} dest={{consul_dest}}] ***** 
changed: [node1]

TASK: [consul | apt name=unzip update_cache=yes] ****************************** 
changed: [node1]

TASK: [consul | unarchive src={{consul_dest}}/{{consul_filename}} dest=/usr/local/bin copy=no] *** 
changed: [node1]

TASK: [consul | copy src=run-consul dest=/usr/local/bin mode=755] ************* 
changed: [node1]

TASK: [consul | copy src=run-consul-client dest=/usr/local/bin mode=755] ****** 
changed: [node1]

TASK: [consul-alerts | file path="{{go_gopath}}/src/github.com/AcalephStorage" state=directory recurse=yes owner=vagrant group=vagrant] *** 
changed: [node1]

TASK: [consul-alerts | file dest="{{go_gopath}}/src/github.com/AcalephStorage/consul-alerts" src=/vagrant state=link] *** 
changed: [node1]

TASK: [consul-alerts | file path="{{go_gopath}}" state=directory owner=vagrant group=vagrant recurse=yes] *** 
changed: [node1]

PLAY RECAP ******************************************************************** 
node1                      : ok=14   changed=13   unreachable=0    failed=0   

==> node2: Importing base box 'consul-alerts'...
==> node2: Matching MAC address for NAT networking...
==> node2: Setting the name of the VM: consul-alerts_node2_1424937779487_41786
==> node2: Clearing any previously set forwarded ports...
==> node2: Fixed port collision for 22 => 2222. Now on port 2200.
==> node2: Clearing any previously set network interfaces...
==> node2: Preparing network interfaces based on configuration...
    node2: Adapter 1: nat
    node2: Adapter 2: hostonly
==> node2: Forwarding ports...
    node2: 22 => 2200 (adapter 1)
==> node2: Running 'pre-boot' VM customizations...
==> node2: Booting VM...
==> node2: Waiting for machine to boot. This may take a few minutes...
    node2: SSH address: 127.0.0.1:2200
    node2: SSH username: vagrant
    node2: SSH auth method: private key
    node2: Warning: Connection timeout. Retrying...
    node2: Warning: Remote connection disconnect. Retrying...
==> node2: Machine booted and ready!
==> node2: Checking for guest additions in VM...
==> node2: Setting hostname...
==> node2: Configuring and enabling network interfaces...
==> node2: Mounting shared folders...
    node2: /vagrant => /Users/devpopol/dev/files/rails/musashibox/consul-alerts
==> node2: Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [node2]

TASK: [git | Install git] ***************************************************** 
changed: [node2]

TASK: [go | Get Go binaries] ************************************************** 
changed: [node2]

TASK: [go | Extract Go binaries] ********************************************** 
changed: [node2]

TASK: [go | Set PATH and GOPATH] ********************************************** 
changed: [node2] => (item=export GOPATH=/home/vagrant)
changed: [node2] => (item=export PATH=$PATH:/usr/local/go/bin)

TASK: [consul | file path={{consul_dest}} state=directory] ******************** 
changed: [node2]

TASK: [consul | get_url url={{consul_download_url}} dest={{consul_dest}}] ***** 
changed: [node2]

TASK: [consul | apt name=unzip update_cache=yes] ****************************** 
changed: [node2]

TASK: [consul | unarchive src={{consul_dest}}/{{consul_filename}} dest=/usr/local/bin copy=no] *** 
changed: [node2]

TASK: [consul | copy src=run-consul dest=/usr/local/bin mode=755] ************* 
changed: [node2]

TASK: [consul | copy src=run-consul-client dest=/usr/local/bin mode=755] ****** 
changed: [node2]

TASK: [consul-alerts | file path="{{go_gopath}}/src/github.com/AcalephStorage" state=directory recurse=yes owner=vagrant group=vagrant] *** 
changed: [node2]

TASK: [consul-alerts | file dest="{{go_gopath}}/src/github.com/AcalephStorage/consul-alerts" src=/vagrant state=link] *** 
changed: [node2]

TASK: [consul-alerts | file path="{{go_gopath}}" state=directory owner=vagrant group=vagrant recurse=yes] *** 
changed: [node2]

PLAY RECAP ******************************************************************** 
node2                      : ok=14   changed=13   unreachable=0    failed=0   

==> node3: Importing base box 'consul-alerts'...
==> node3: Matching MAC address for NAT networking...
==> node3: Setting the name of the VM: consul-alerts_node3_1424938170341_64671
==> node3: Clearing any previously set forwarded ports...
==> node3: Fixed port collision for 22 => 2200. Now on port 2201.
==> node3: Clearing any previously set network interfaces...
==> node3: Preparing network interfaces based on configuration...
    node3: Adapter 1: nat
    node3: Adapter 2: hostonly
==> node3: Forwarding ports...
    node3: 22 => 2201 (adapter 1)
==> node3: Running 'pre-boot' VM customizations...
==> node3: Booting VM...
==> node3: Waiting for machine to boot. This may take a few minutes...
    node3: SSH address: 127.0.0.1:2201
    node3: SSH username: vagrant
    node3: SSH auth method: private key
    node3: Warning: Connection timeout. Retrying...
    node3: Warning: Remote connection disconnect. Retrying...
==> node3: Machine booted and ready!
==> node3: Checking for guest additions in VM...
==> node3: Setting hostname...
==> node3: Configuring and enabling network interfaces...
==> node3: Mounting shared folders...
    node3: /vagrant => /Users/devpopol/dev/files/rails/musashibox/consul-alerts
==> node3: Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [node3]

TASK: [git | Install git] ***************************************************** 
changed: [node3]

TASK: [go | Get Go binaries] ************************************************** 
changed: [node3]

TASK: [go | Extract Go binaries] ********************************************** 
changed: [node3]

TASK: [go | Set PATH and GOPATH] ********************************************** 
changed: [node3] => (item=export GOPATH=/home/vagrant)
changed: [node3] => (item=export PATH=$PATH:/usr/local/go/bin)

TASK: [consul | file path={{consul_dest}} state=directory] ******************** 
changed: [node3]

TASK: [consul | get_url url={{consul_download_url}} dest={{consul_dest}}] ***** 
changed: [node3]

TASK: [consul | apt name=unzip update_cache=yes] ****************************** 
changed: [node3]

TASK: [consul | unarchive src={{consul_dest}}/{{consul_filename}} dest=/usr/local/bin copy=no] *** 
changed: [node3]

TASK: [consul | copy src=run-consul dest=/usr/local/bin mode=755] ************* 
changed: [node3]

TASK: [consul | copy src=run-consul-client dest=/usr/local/bin mode=755] ****** 
changed: [node3]

TASK: [consul-alerts | file path="{{go_gopath}}/src/github.com/AcalephStorage" state=directory recurse=yes owner=vagrant group=vagrant] *** 
changed: [node3]

TASK: [consul-alerts | file dest="{{go_gopath}}/src/github.com/AcalephStorage/consul-alerts" src=/vagrant state=link] *** 
changed: [node3]

TASK: [consul-alerts | file path="{{go_gopath}}" state=directory owner=vagrant group=vagrant recurse=yes] *** 
changed: [node3]

PLAY RECAP ******************************************************************** 
node3                      : ok=14   changed=13   unreachable=0    failed=0   
```

### Run server

```
devpopol@popol consul-alerts (vagrant-support) $ vagrant ssh node1
run-run-conWelcome to Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

 System information disabled due to load higher than 1.0

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Thu Feb 26 08:02:49 2015 from 10.0.2.2
_____________________________________________________________________
WARNING! Your environment specifies an invalid locale.
 This can affect your user experience significantly, including the
 ability to manage packages. You may install the locales by running:

   sudo apt-get install language-pack-UTF-8
     or
   sudo locale-gen UTF-8

To see all available language packs, run:
   apt-cache search "^language-pack-[a-z][a-z]$"
To disable this message for all users, run:
   sudo touch /var/lib/cloud/instance/locale-check.skip
_____________________________________________________________________

vagrant@node1:~$ run-consul
vagrant@node1:~$ nohup: appending output to 'nohup.out'

vagrant@node1:~$ exit
logout
Connection to 127.0.0.1 closed.
```

### Run client for node2

```
devpopol@popol consul-alerts (vagrant-support) $ vagrant ssh node2
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Thu Feb 26 08:03:32 UTC 2015

  System load:  0.91              Processes:           90
  Usage of /:   2.7% of 39.34GB   Users logged in:     0
  Memory usage: 26%               IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 192.168.100.51

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Thu Feb 26 08:09:20 2015 from 10.0.2.2
_____________________________________________________________________
WARNING! Your environment specifies an invalid locale.
 This can affect your user experience significantly, including the
 ability to manage packages. You may install the locales by running:

   sudo apt-get install language-pack-UTF-8
     or
   sudo locale-gen UTF-8

To see all available language packs, run:
   apt-cache search "^language-pack-[a-z][a-z]$"
To disable this message for all users, run:
   sudo touch /var/lib/cloud/instance/locale-check.skip
_____________________________________________________________________

vagrant@node2:~$ run-consul-client
vagrant@node2:~$ nohup: appending output to 'nohup.out'

vagrant@node2:~$ consul join 192.168.100.50
Successfully joined cluster by contacting 1 nodes.
vagrant@node2:~$ exit
logout
Connection to 127.0.0.1 closed.
```

### Run client for node3

```
devpopol@popol consul-alerts (vagrant-support) $ vagrant ssh node3
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

 System information disabled due to load higher than 1.0

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Thu Feb 26 08:24:38 2015 from 10.0.2.2
_____________________________________________________________________
WARNING! Your environment specifies an invalid locale.
 This can affect your user experience significantly, including the
 ability to manage packages. You may install the locales by running:

   sudo apt-get install language-pack-UTF-8
     or
   sudo locale-gen UTF-8

To see all available language packs, run:
   apt-cache search "^language-pack-[a-z][a-z]$"
To disable this message for all users, run:
   sudo touch /var/lib/cloud/instance/locale-check.skip
_____________________________________________________________________

vagrant@node3:~$ run-consul-client
vagrant@node3:~$ nohup: appending output to 'nohup.out'
vagrant@node3:~$ consul join 192.168.100.50
Successfully joined cluster by contacting 1 nodes.
```

### See the members of the cluster

```
vagrant@node3:~$ consul members
Node   Address         Status  Type    Build  Protocol
node3  10.0.2.15:8301  alive   client  0.5.0  2
node1  10.0.2.15:8301  alive   server  0.5.0  2
```

Not sure why it doesn't show node2 :|

**Comment by stefanymarie** [comment]
i got this
```
vagrant@node1:~$ consul members
Node   Address         Status  Type    Build  Protocol
node1  10.0.2.15:8301  alive   server  0.5.0  2
node2  10.0.2.15:8301  failed  client  0.5.0  2
node3  10.0.2.15:8301  failed  client  0.5.0  2
```
```
vagrant@node2:~$ cat nohup.out 
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: 'node2'
        Datacenter: 'dc1'
            Server: false (bootstrap: false)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 10.0.2.15 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2015/03/02 04:31:34 [INFO] serf: EventMemberJoin: node2 10.0.2.15
    2015/03/02 04:31:34 [ERR] agent: failed to sync remote state: No known Consul servers
    2015/03/02 04:31:47 [INFO] agent.rpc: Accepted client: 127.0.0.1:54738
    2015/03/02 04:31:47 [INFO] agent: (LAN) joining: [192.168.100.50]
    2015/03/02 04:31:47 [INFO] serf: EventMemberJoin: node1 10.0.2.15
    2015/03/02 04:31:47 [INFO] agent: (LAN) joined: 1 Err: <nil>
    2015/03/02 04:31:47 [INFO] consul: adding server node1 (Addr: 10.0.2.15:8300) (DC: dc1)
    2015/03/02 04:31:47 [WARN] memberlist: Got ping for unexpected node 'node1'
    2015/03/02 04:31:48 [ERR] agent: failed to sync remote state: rpc error: failed to get conn: dial tcp 10.0.2.15:8300: connection refused
    2015/03/02 04:31:48 [INFO] memberlist: Suspect node1 has failed, no acks received
    2015/03/02 04:31:49 [WARN] memberlist: Got ping for unexpected node 'node1'
    2015/03/02 04:31:50 [INFO] memberlist: Suspect node1 has failed, no acks received
    2015/03/02 04:31:51 [WARN] memberlist: Got ping for unexpected node 'node1'
    2015/03/02 04:31:52 [INFO] memberlist: Suspect node1 has failed, no acks received
    2015/03/02 04:31:52 [WARN] memberlist: Got ping for unexpected node 'node1'
    2015/03/02 04:31:53 [INFO] memberlist: Suspect node1 has failed, no acks received
    2015/03/02 04:31:53 [INFO] memberlist: Marking node1 as failed, suspect timeout reached
    2015/03/02 04:31:53 [INFO] serf: EventMemberFailed: node1 10.0.2.15
    2015/03/02 04:31:53 [INFO] consul: removing server node1 (Addr: 10.0.2.15:8300) (DC: dc1)
    2015/03/02 04:32:04 [INFO] serf: attempting reconnect to node1 10.0.2.15:8301
    2015/03/02 04:32:07 [ERR] agent: failed to sync remote state: No known Consul servers
    2015/03/02 04:32:32 [ERR] agent: failed to sync remote state: No known Consul servers
    2015/03/02 04:32:34 [INFO] serf: attempting reconnect to node1 10.0.2.15:8301
    2015/03/02 04:32:51 [ERR] agent: failed to sync remote state: No known Consul servers
```
maybe `-bind` option should be provided when running the agent? I tried running the agent manually
```
vagrant@node1:~$ sudo consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul \
-bind=192.168.100.50
```
```
vagrant@node2:~$ sudo consul agent -data-dir /tmp/consul -bind=192.168.100.51
```
```
vagrant@node3:~$ sudo consul agent -data-dir /tmp/consul -bind=192.168.100.52
```
and i got this
```
vagrant@node1:~$ consul members
Node   Address              Status  Type    Build  Protocol
node1  192.168.100.50:8301  alive   server  0.5.0  2
node2  192.168.100.51:8301  alive   client  0.5.0  2
node3  192.168.100.52:8301  alive   client  0.5.0  2
```

**Comment by devpopol** [comment]
thanks @stefanymarie, i'll add the bind option.

**Comment by devpopol** [comment]
### Provision

```
devpopol@popol consul-alerts (vagrant-support) $ vagrant up
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node3' up with 'virtualbox' provider...
==> node1: Importing base box 'consul-alerts'...
==> node1: Matching MAC address for NAT networking...
==> node1: Setting the name of the VM: consul-alerts_node1_1425278784864_47207
==> node1: Clearing any previously set forwarded ports...
==> node1: Clearing any previously set network interfaces...
==> node1: Preparing network interfaces based on configuration...
    node1: Adapter 1: nat
    node1: Adapter 2: hostonly
==> node1: Forwarding ports...
    node1: 22 => 2222 (adapter 1)
==> node1: Running 'pre-boot' VM customizations...
==> node1: Booting VM...
==> node1: Waiting for machine to boot. This may take a few minutes...
    node1: SSH address: 127.0.0.1:2222
    node1: SSH username: vagrant
    node1: SSH auth method: private key
    node1: Warning: Connection timeout. Retrying...
    node1: Warning: Remote connection disconnect. Retrying...
==> node1: Machine booted and ready!
==> node1: Checking for guest additions in VM...
==> node1: Setting hostname...
==> node1: Configuring and enabling network interfaces...
==> node1: Mounting shared folders...
    node1: /vagrant => /Users/devpopol/dev/files/rails/musashibox/consul-alerts
==> node2: Importing base box 'consul-alerts'...
==> node2: Matching MAC address for NAT networking...
==> node2: Setting the name of the VM: consul-alerts_node2_1425278827809_64496
==> node2: Clearing any previously set forwarded ports...
==> node2: Fixed port collision for 22 => 2222. Now on port 2200.
==> node2: Clearing any previously set network interfaces...
==> node2: Preparing network interfaces based on configuration...
    node2: Adapter 1: nat
    node2: Adapter 2: hostonly
==> node2: Forwarding ports...
    node2: 22 => 2200 (adapter 1)
==> node2: Running 'pre-boot' VM customizations...
==> node2: Booting VM...
==> node2: Waiting for machine to boot. This may take a few minutes...
    node2: SSH address: 127.0.0.1:2200
    node2: SSH username: vagrant
    node2: SSH auth method: private key
    node2: Warning: Connection timeout. Retrying...
    node2: Warning: Remote connection disconnect. Retrying...
==> node2: Machine booted and ready!
==> node2: Checking for guest additions in VM...
==> node2: Setting hostname...
==> node2: Configuring and enabling network interfaces...
==> node2: Mounting shared folders...
    node2: /vagrant => /Users/devpopol/dev/files/rails/musashibox/consul-alerts
==> node3: Importing base box 'consul-alerts'...
==> node3: Matching MAC address for NAT networking...
==> node3: Setting the name of the VM: consul-alerts_node3_1425278867694_31659
==> node3: Clearing any previously set forwarded ports...
==> node3: Fixed port collision for 22 => 2200. Now on port 2201.
==> node3: Clearing any previously set network interfaces...
==> node3: Preparing network interfaces based on configuration...
    node3: Adapter 1: nat
    node3: Adapter 2: hostonly
==> node3: Forwarding ports...
    node3: 22 => 2201 (adapter 1)
==> node3: Running 'pre-boot' VM customizations...
==> node3: Booting VM...
==> node3: Waiting for machine to boot. This may take a few minutes...
    node3: SSH address: 127.0.0.1:2201
    node3: SSH username: vagrant
    node3: SSH auth method: private key
    node3: Warning: Connection timeout. Retrying...
    node3: Warning: Remote connection disconnect. Retrying...
==> node3: Machine booted and ready!
==> node3: Checking for guest additions in VM...
==> node3: Setting hostname...
==> node3: Configuring and enabling network interfaces...
==> node3: Mounting shared folders...
    node3: /vagrant => /Users/devpopol/dev/files/rails/musashibox/consul-alerts
==> node3: Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [node1]
ok: [node2]
ok: [node3]

TASK: [git | Install git] ***************************************************** 
changed: [node3]
changed: [node1]
changed: [node2]

TASK: [go | Get Go binaries] ************************************************** 
changed: [node3]
changed: [node2]
changed: [node1]

TASK: [go | Extract Go binaries] ********************************************** 
changed: [node1]
changed: [node2]
changed: [node3]

TASK: [go | Set PATH and GOPATH] ********************************************** 
changed: [node3] => (item=export GOPATH=/home/vagrant)
changed: [node2] => (item=export GOPATH=/home/vagrant)
changed: [node1] => (item=export GOPATH=/home/vagrant)
changed: [node2] => (item=export PATH=$PATH:/usr/local/go/bin)
changed: [node3] => (item=export PATH=$PATH:/usr/local/go/bin)
changed: [node1] => (item=export PATH=$PATH:/usr/local/go/bin)

TASK: [consul | file path={{consul_dest}} state=directory] ******************** 
changed: [node2]
changed: [node3]
changed: [node1]

TASK: [consul | get_url url={{consul_download_url}} dest={{consul_dest}}] ***** 
changed: [node1]
changed: [node2]
changed: [node3]

TASK: [consul | apt name=unzip update_cache=yes] ****************************** 
changed: [node3]
changed: [node1]
changed: [node2]

TASK: [consul | unarchive src={{consul_dest}}/{{consul_filename}} dest=/usr/local/bin copy=no] *** 
changed: [node3]
changed: [node1]
changed: [node2]

TASK: [consul | template src=run-consul dest=/usr/local/bin mode=755] ********* 
changed: [node1]
changed: [node3]
changed: [node2]

TASK: [consul | template src=run-consul-client dest=/usr/local/bin mode=755] *** 
changed: [node2]
changed: [node3]
changed: [node1]

TASK: [consul-alerts | file path="{{go_gopath}}/src/github.com/AcalephStorage" state=directory recurse=yes owner=vagrant group=vagrant] *** 
changed: [node3]
changed: [node2]
changed: [node1]

TASK: [consul-alerts | file dest="{{go_gopath}}/src/github.com/AcalephStorage/consul-alerts" src=/vagrant state=link] *** 
changed: [node1]
changed: [node2]
changed: [node3]

TASK: [consul-alerts | file path="{{go_gopath}}" state=directory owner=vagrant group=vagrant recurse=yes] *** 
changed: [node2]
changed: [node1]
changed: [node3]

PLAY RECAP ******************************************************************** 
node1                      : ok=13   changed=5    unreachable=0    failed=0   
node2                      : ok=13   changed=5    unreachable=0    failed=0   
node3                      : ok=13   changed=5    unreachable=0    failed=0   
```

### Server setup (node1)

```
devpopol@popol consul-alerts (vagrant-support) $ vagrant ssh node1

vagrant@node1:~$ run-consul
vagrant@node1:~$ nohup: appending output to 'nohup.out'

vagrant@node1:~$ exit
logout
Connection to 127.0.0.1 closed.
```
### Client setup (node2)

```
devpopol@popol consul-alerts (vagrant-support) $ vagrant ssh node2

vagrant@node2:~$ run-consul-client
nohup: appending output to 'nohup.out'
Successfully joined cluster by contacting 1 nodes.
vagrant@node2:~$ exit
logout
Connection to 127.0.0.1 closed.
```

### Client setup (node3)

```
devpopol@popol consul-alerts (vagrant-support) $ vagrant ssh node3
vagrant@node3:~$ run-consul-client
nohup: appending output to 'nohup.out'
Successfully joined cluster by contacting 1 nodes.
```

### Check status

```
vagrant@node3:~$ consul members
Node   Address              Status  Type    Build  Protocol
node1  192.168.100.50:8301  alive   server  0.5.0  2
node3  192.168.100.52:8301  alive   client  0.5.0  2
node2  192.168.100.51:8301  alive   client  0.5.0  2
```

**Pull request closed without merging**
