### PR TITLE
Add notifications support for mattermost

### PR DESCRIPTION
**Pull request by jhixson74**

### CODE REVIEW

**Comment by jhixson74** [comment]
Yay? Nay? ;-)

**Comment by fusiondog** [comment]
Hey, looks ok. The new option override refactor seems to have introduced a few conflicts.  Please take a look at those and I can take a look at merging in this provider.

**Comment by Gerrrr** [comment]
Hey @jhixson74 
Let me know if you need any help with the conflicts caused by the option override, I'd love to support.

**Comment by jhixson74** [comment]
I thought I had this merged with no conflicts. Boo. Blah. ;-)

**Comment by jhixson74** [comment]
ok, merged. I tested this and it's working.

**Pull request merged**
