### PR TITLE
More visible output in consul slack alerts

### PR DESCRIPTION
**Pull request by udzura**
Hi, I have made a more stylish slack alert format.

Set `consul-alerts/config/notifiers/slack/detailed` to `true` to enable this.

### CODE REVIEW

**Comment by rrreeeyyy** [comment]
:+1:

**Comment by thomascramer** [comment]
+1

**Comment by lyrixx** [comment]
:+1:

**Comment by josefzamrzla** [comment]
+1

**Comment by josefzamrzla** [comment]
Great news! When we can expect the release?

**Pull request merged**
